ionelmc/cookiecutter-pylibrary

- .gitignore
- {{cookiecutter.repo_name}}/.gitignore
1. Add pyvenv and virtualenv environments
2. drop .coverage because it's already in the list
3. add IntelliJ IDEA config file
Thanks for the merge.
> Small improvements for .gitignore

- {{cookiecutter.repo_name}}/ci/templates/tox.ini
- {{cookiecutter.repo_name}}/setup.py
See https://github.com/ionelmc/cookiecutter-pylibrary/issues/29#issuecomment-144953556
Build where this fix was introduced:
* [travis](https://travis-ci.org/cmeeren/aacgmv2/builds/83277337)
* [codecov](https://codecov.io/github/cmeeren/aacgmv2?ref=2bb8c0655cd6ceabc4ad152a638f5cac384b671b&view=all)
Build where `CFLAGS=-coverage` was removed entirely:
* [travis](https://travis-ci.org/cmeeren/aacgmv2/builds/83255645)
* [codecov](https://codecov.io/github/cmeeren/aacgmv2?ref=3180a43c812bc251159a6455cb1deed390a34192&view=all)
Build where `CFLAGS=-coverage` was present and numpy install failed:
* [travis](https://travis-ci.org/cmeeren/aacgmv2/builds/83117034)
> use CFLAGS=-coverage for current package only, not deps

- {{cookiecutter.repo_name}}/.travis.yml
- {{cookiecutter.repo_name}}/ci/templates/.travis.yml
- {{cookiecutter.repo_name}}/ci/templates/tox.ini
- {{cookiecutter.repo_name}}/tox.ini
This incorporates follow-up changes based on feedback for #35.
> travis: cache pip, tune libsigsegv, add pytest-travis-fold

- {{cookiecutter.repo_name}}/docs/conf.py
``napoleon_use_ivar=True`` will make class attributes look like the parameters section instead of looking like methods.
``napoleon_use_rtype=False`` will make the return type inline, which gives a consistent look between functions with multiple returns (where the type is always inline) and functions with single returns (where the return type is on its own by default).
Attributes ``year``, ``refh``, ``datafile`` looking like methods (default):
Attributes looking like parameters (proposed change):
Return type in its own section when one variable is returned, and inline if multiple variables are returned (default):
Return type always inline for consistency (proposed change):
> Update napoleon config

- {{cookiecutter.repo_name}}/CONTRIBUTING.rst
If you mean "code contributions", I think that should be clarified here. When reading it without the clarification I get the impression that e.g. donations are welcome.
I have no idea what's up with the "detox" line, I did absolutely not change that (it happened twice, must be a GH bug).
> Specify "code contributions"

- {{cookiecutter.repo_name}}/docs/index.rst
With this change, the title (html title, shown in search engines) on the main ReadTheDocs page (projectname.readthedocs.org) is:
"Contents - \<projectname\> \<version\> documentation"
instead of the rather wordy and self-repeating:
"Welcome to \<projectname\>'s documentation - \<projectname\> \<version\> documentation"
This is just a suggestion, and there may be better ways to fix the page title. I like it though, because the package name is (using the default RTD style) always in the upper left corner anyway, and people probably don't need to be told that this is, in fact, the packages documentation (as opposed to what? :P )
I'm not 100% sure the heading level is correct though.
> Change index.rst main heading

- {{cookiecutter.repo_name}}/README.rst
- {{cookiecutter.repo_name}}/docs/readme.rst
Since README.rst is included in docs/index.rst, the heading will be shown in the ReadTheDocs menu. I don't think the project name is especially informative as a title in the menu, so I'm using "Overview" here in my packages. The package name is shown at the top on PyPI anyway.
Just a suggestion. :)
> Update heading in README.rst

- README.rst
- {{cookiecutter.repo_name}}/ci/appveyor-bootstrap.py
- {{cookiecutter.repo_name}}/tox.ini
@ionelmc This pull request removes a few references to python 2.6. It's no longer included in the test matrix.
Python 2.6 hasn't been supported by Python core in some time, with the last release being from October 2013.
Thanks for making this incredibly useful template!
> Remove several references to python 2.6

- {{cookiecutter.repo_name}}/tox.ini
if no c extension support, dont include "extension-coveralls", 
also suppose, if not use coverall, "extension-coveralls" should not be included too.
> if no c extension support, dont include "extension-coveralls"

- README.rst
- cookiecutter.json
- {{cookiecutter.repo_name}}/docs/conf.py
- {{cookiecutter.repo_name}}/docs/requirements.txt
This is a partial fix for #54. This pull request ensures that `sphinx_rtd_theme` is installed in the docs environment if that was chosen by the user during project generation. I changed the `sphinx_theme` configuration value from `readthedocs` to `sphinx_rtd_theme` because it made the code more consistent and avoided hard-coding in a couple spots, but I understand if that's not the solution that is preferred.
The second commit simplifies the inclusion of `sphinx_rtd_theme`, as `'sphinx_rtd_theme'` is a special value recognized by Sphinx. Feel free to cherry pick, though!
Building the docs is still failing after these changes have been applied, but the issue is no longer with `sphinx_rtd_theme`. See my updated #54 for more information.
> Partial fix for Sphinx 1.4 build failures

- README.rst
Add missing template variables (author, email, etc.):
- full_name,
- email,
- website,
- github_username,
- project_short_description,
- release_date,
- year,
- version,
- c_extension_cython.
Add "argparse" in ``command_line_interface`` option.
Add clarifications on some options.
Fix wrong reference to ``Travis-CI``.
> Add missing template variables in README.rst

- {{cookiecutter.repo_name}}/setup.cfg
- {{cookiecutter.repo_name}}/setup.py
- {{cookiecutter.repo_name}}/tox.ini
I change the ``setup.py`` to generate the console script entry point in "argparse" is chosen (not only "plain" or "click").
I add a section for ``nosetests`` in ``setup.cfg`` if "nose" if chosen and remove the ``pytest`` section.
I fix the ``nosetests`` command in ``tox.ini``: "tests" is removed because it is interpreted as being a package instead of a directory.
> Template fix: missing entry point if "argparse" and config for "nosetests"

- {{cookiecutter.repo_name}}/src/{{cookiecutter.package_name.replace('-','_')}}/cli.py
This should fix issue #66, and I've tested locally, just hard to tell if it's a missing \n on 53 or whether 54 removes the \n on 53 when it removes itself which causes one of the PEP issues.
> Add trailing minus to remove blank newline

- {{cookiecutter.repo_name}}/ci/appveyor-bootstrap.py
- {{cookiecutter.repo_name}}/ci/appveyor-download.py
- {{cookiecutter.repo_name}}/ci/bootstrap.py
The generated ``ci`` scripts appears to have some awkwardness:
- too broad exception catching (when calling ``check_output`` or ``check_call``).
- PEP8 warnings: order of imports, newlines.
- local variable may not be defined (when checking "coverage_flags" and "environment_variables" in ``conf``).
Also notice that: ``python ci/bootstrap.py`` won't work if ``tox`` isn't installed globally or in the project's virtualenv, (in my environment, I use an ``alias`` for ``tox``). So, I add a warning.
Enjoy.
> Improve code style (PEP8) of ``{{cookiecutter.repo_name}}/ci`` scripts.

- {{cookiecutter.repo_name}}/CONTRIBUTING.rst
Running `$ tox -e docs` warns about a permanent redirect:
```
writing output... [ 33%] contributing
...
(line   52) redirect  http://tox.readthedocs.org/en/latest/install.html\
- permanently to http://tox.readthedocs.io/en/latest/install.html
...
```
This change fixes it:
```
(line   52) ok        http://tox.readthedocs.io/en/latest/install.html
```
> Fix redirect warning for tox.readthedocs.org -> tox.readthedocs.io 

- ci/test.sh
This should fix the incorrect behaviour of the tox tests on MacOS.
> Fix for BSD sed on MacOS

- {{cookiecutter.repo_name}}/setup.py
Regardless of what license you pick in the cookiecutter dialog, the resulting setup.py script specifies the license as "BSD"
> Fix license not being set correctly in setup script

- {{cookiecutter.repo_name}}/.travis.yml
- {{cookiecutter.repo_name}}/appveyor.yml
- {{cookiecutter.repo_name}}/ci/appveyor-bootstrap.py
- {{cookiecutter.repo_name}}/ci/templates/appveyor.yml
- {{cookiecutter.repo_name}}/setup.py
- {{cookiecutter.repo_name}}/tox.ini
Python 3.3 reached end-of-life on 2017-09-29.
New projects should not be using end-of-life versions of python.
See the Python [branch status](https://devguide.python.org/#branchstatus).
> Remove python 3.3 as its past end-of-life

- README.rst
- {{cookiecutter.repo_name}}/tox.ini
https://testrun.org/ is just a squatted domain. Official docs are under https://tox.readthedocs.io/
> Update tox docs links

- CHANGELOG.rst
- README.rst
- {{cookiecutter.repo_name}}/.cookiecutterrc
- {{cookiecutter.repo_name}}/README.rst
https://pypi.python.org/pypi/<pkg-name> redirects permanently to https://pypi.org/project/<pkg-name>
> Update PyPI URLs (PyPI migrated to pypi.org)

- {{cookiecutter.repo_name}}/tox.ini
This removes a [testenv:bootstrap] section in tox.ini that appears (?) to be completely redundant, duplicating the [testenv:bootstrap] above it so that those settings are in two places (so that changing the settings above has no effect, because they are overridden by the settings below).
The only settings left inside the if-block are the settings that actually depend on if cookiecutter.test_matrix_configurator == "yes".
This uses #118 to pass the Travis CI build.
> Remove redundant settings in tox.ini

- {{cookiecutter.repo_name}}/ci/bootstrap.py
- {{cookiecutter.repo_name}}/tox.ini
Resolves #121.
Since tox is required by the bootstrap.py script (to run tox --listenvs), this adds tox to the dependencies and then invokes tox the same way it's invoked in https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/hooks/post_gen_project.py.
This relies on #117.
> bootstrap tox

- {{cookiecutter.repo_name}}/setup.cfg
- {{cookiecutter.repo_name}}/setup.py
This is sort of a feature request: This changes setup.py and setup.cfg so that in a newly-created package, by default, python setup.py test will run whatever test runner was selected.
This required collapsing multiple settings of `setup_requires` in setup.py so that we could include the necessary pytest-runner and still include cffi and cython in `setup_requires` when needed. (I can split of that collapsing as a separate branch if that would be clearer.)
The best way I could think of to allow the jinja2 if-blocks to either add or not add to `setup_requires` was to use list concatenation.
> Use test runner for setup py test

- README.rst
- cookiecutter.json
- hooks/post_gen_project.py
- {{cookiecutter.repo_name}}/setup.cfg
Minor suggestion for pytest default settings --- going for least astonishment, someone who puts a `test_*` file in `src/` (that is, a test to be installed with the package) probably will not be surprised or confused if `pytest` finds and runs those tests.
> Run installable tests

- hooks/post_gen_project.py
https://github.com/ionelmc/cookiecutter-pylibrary/commit/c426c169d0bec5faa5dace5f2c59865595ca77d8 removed appveyor-download.py, but post_gen_project.py still tries to unlink the non-existing file. This causes the generation to crash if cookiecutter.appveyor == 'no'.
> Remove os.unlink(join('ci', 'appveyor-download.py'))

- README.rst
- cookiecutter.json
- {{cookiecutter.repo_name}}/README.rst
Currently, out of the box, `tox -e docs` crashes if documentation is not hosted on readthedocs, complaining of a broken link.
The adds a way to enter a custom URL if documentation is hosted in a non-standard location such as GitHub Pages or GitLab Pages.
> Allow non-readthedocs documentation hosting

- {{cookiecutter.repo_name}}/tox.ini
This makes it so that the test command does not specify the tests directory.
This only changes things for the case of allow_tests_inside_package, but honestly I think we could just remove the specification of the tests directory regardless, with no jinja2 switch. The config file already specifies where the tests are; if we specify the directory in the command, I'm pretty sure that's actually overriding the config file and making the config file superfluous.
> Run installed tests on CI runner

- hooks/post_gen_project.py
- {{cookiecutter.repo_name}}/CHANGELOG.rst
to match the length of `datetime.date.today().strftime("%Y-%m-%d")`.
This is hideously ugly, but there seems to be no way to call `datetime.date.today().strftime("%Y-%m-%d")` from jinja2 itself, nor can a cookiecutter pre_gen_project hook change the `cookiecutter.release_date` argument. So the only alternative to get a matching underline would be for the post_gen_project hook that inserts the date also insert an appropriate length of "-". (Which...I guess that would also be an option, if you'd prefer that.)
> Fix the changelog header-length calculation

- .travis.yml
- ci/test.sh
…if we cannot push python-nameless for any reason.
Hrm. Looks like maybe Travis has PyPy 3.2.4? I'm not sure.
```
pypy3-cover create: /home/travis/build/ionelmc/cookiecutter-pylibrary/python-nameless/.tox/pypy3-cover
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/ionelmc/cookiecutter-pylibrary/python-nameless/.tox/pypy3-cover/log/pypy3-cover-0.log
================================== log start ===================================
Running virtualenv with interpreter /opt/python/pypy3-2.4.0/bin/pypy3
New pypy executable in /home/travis/build/ionelmc/cookiecutter-pylibrary/python-nameless/.tox/pypy3-cover/bin/pypy3
Also creating executable in /home/travis/build/ionelmc/cookiecutter-pylibrary/python-nameless/.tox/pypy3-cover/bin/pypy
Installing setuptools, pip, wheel... …
```
> Test python-nameless locally

- ci/test.sh
This makes ENV=matrix-cext pass on Travis.
Note that three builds are still failing on Travis, but those failures are not caused by this change --- see #146 and #147.
> Remove pypy3 regardless of which side the comma is on.

- {{cookiecutter.repo_name}}/setup.py
(rather than hosted).
Resolves #146.
This has three Travis failures, but those will be fixed by #145 and #149.
> Use a file:// URL when the repository is local on the filesystem

- {{cookiecutter.repo_name}}/pyproject.toml
- {{cookiecutter.repo_name}}/setup.cfg
- {{cookiecutter.repo_name}}/setup.py
…that includes both pytest-runner and setuptools_scm as appropriate.
Resolves #147.
Note that this still has two Travis failures on ENV=pure-private (due to #146) and ENV=matrix-cext (that will be fixed by #145).
> Define block setup_requires_interior

- README.rst
`twine register` is no longer required or supported for PyPI.
```
HTTPError: 410 Client Error: Project pre-registration is no longer required or supported, upload your files instead. for url: https://upload.pypi.org/legacy/
```
I could upload just by doing:
```
twine upload --skip-existing dist/*.whl dist/*.gz
```
* removed `twine register` from `README`
(i just noticed it was already reported as issue)
Solves #104
> removed twine register command

- CONTRIBUTING.rst
- {{cookiecutter.repo_name}}/CONTRIBUTING.rst
- {{cookiecutter.repo_name}}/ci/templates/tox.ini
- {{cookiecutter.repo_name}}/docs/conf.py
- {{cookiecutter.repo_name}}/setup.py
- {{cookiecutter.repo_name}}/tox.ini
- it's cumbersome as you have to whitelist almost all programming jargon and names
- it's mostly and useless appendix - doesn't run in CI
- it relies on the unmaintained pyenchant lib
@dHannasch @joaomcteixeira now only thing left is to recommend some alternatives to checking spelling besides pycharm/other-big-IDE.
Closes #163 #160 #159 #12.
> Remove the spell env

- hooks/post_gen_project.py
- {{cookiecutter.repo_name}}/.readthedocs.yml
Adds a ``.readthedocs.yml`` config file, which configures the Read the Docs build.
In the docs build, the package is installed using pip so the autodoc feature works. 
Since this config file overrides the advanced settings as configured in the UI, the user does not need to activate the virtualenv setting anymore. 
The ``.readthedocs.yml`` is removed if ``cookiecutter.sphinx_docs == "no" `` or if ``"readthedocs" is not in cookiecutter.sphinx_docs_hosting``. 
Implements changes suggested by #176.
> Add .readthedocs.yml config file to configure Read the Docs build.

- {{cookiecutter.repo_name}}/.readthedocs.yml
Fixes #185 
This indentation changes fixes a Read the Docs yaml parsing failure,
which surfaces as this Error:
Problem in your project's configuration. Parse error in .readthedocs.yml: YAML:
mapping values are not allowed here in "<unicode string>"
line 26, column 13: path: .
See more before-and-after in my r2b2 project: https://github.com/gwexploratoryaudits/r2b2/pull/5
Discussion at https://stackoverflow.com/a/41236822/507544
> Fix syntax error in .readthedocs.yml

- .gitignore
IPython / Jupyter Notebook checkpoints should be ignored.
Following example at https://github.com/ipython/ipynb/blob/master/.gitignore
> Ignore  Notebook Checkpoints .ipynb_checkpoints

- {{cookiecutter.repo_name}}/docs/conf.py
Shift deletion of whitespace so that isort does not complain if cookiecutter.setup_py_uses_setuptools_scm is no and thus `import trackback` is left out of conf.py.
This PR works (see https://gitlab.com/dHannasch/python-nameless/-/pipelines), though of course the Travis builds are still failing for unrelated reasons.
> Make isort pass if cookiecutter.setup_py_uses_setuptools_scm is no

- .travis.yml
- ci/test.sh
We could actually be even more specific than this, and allow system site packages for every individual testenv except the PyPy ones, or specifying `--no-build-isolation` for PyPy, but I'm not immediately sure how and it likely wouldn't be worth the bother.
> Use --sitepackages to accelerate when we can.

- .appveyor.yml
- .travis.yml
- ci/templates/.appveyor.yml
- ci/templates/.travis.yml
- ci/test.sh
- {{cookiecutter.repo_name}}/ci/templates/.travis.yml
- {{cookiecutter.repo_name}}/setup.cfg
- {{cookiecutter.repo_name}}/setup.py
- {{cookiecutter.repo_name}}/tox.ini
So it turns out that I enabled system site packges (for speed) and that caused problems when building the pip517 wheels (since pip doesn't account for that options it reinstalls cffi and you get the version mismatch). The unavailablebackend issue is gone too (not sure what actually caused it but I suspect it's a hidden cffi mismatch error).
I've switched the virtualization to lxd to get fast builds again.
Passing builds with publishing disabled here:
https://travis-ci.org/github/ionelmc/cookiecutter-pylibrary/builds/740417786
https://travis-ci.org/github/ionelmc/cookiecutter-pylibrary/builds/740360626
Closes #206. Closes #203. Closes #202. Closes #204. Closes #207. Closes #208.
> Simpler fix for the cffi version mismatch and backend problems

- hooks/post_gen_project.py
so that tox does not hang indefinitely if there is no active Internet connection.
> Use tox --sitepackages for the tox -e bootstrap call
